
FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
EXPOSE 80
CMD ["streamlit", "run", "Streamlit/basic_ui.py", "--server.port=80", "--server.address=0.0.0.0"]